/*
 * Copyright 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package android.hardware.security.see.authmgr;

parcelable AppRequest {
    // The name of the service for which an app is requesting a connection.
    String serviceName;

    // A unique, static identifier for this app. This should be mixed into the derivation of
    // diceLeaf.
    byte[] appId;

    // The DICE leaf node of the app requesting a connection.
    byte[] diceLeaf;

    // The sealing policy for the app. This should be generated by the client in such a way
    // as to prevent rollback of the app once successfully authenticated and authorized by
    // the server.
    byte[] dicePolicy;

    // A one-time random token that identifies the connection attempt. This token should not be
    // re-used across requests.
    byte[] token;
}
