LOCAL_SRC_FILES += ChargerConfigs.cpp

# TODO: Use $(strip ...) ?
ifneq ($(TARGET_HEALTHD_DRAW_SPLIT_SCREEN),)
    LOCAL_CFLAGS += -DHEALTHD_DRAW_SPLIT_SCREEN=$(TARGET_HEALTHD_DRAW_SPLIT_SCREEN)
endif

ifneq ($(TARGET_HEALTHD_DRAW_SPLIT_OFFSET),)
    LOCAL_CFLAGS += -DHEALTHD_DRAW_SPLIT_OFFSET=$(TARGET_HEALTHD_DRAW_SPLIT_OFFSET)
endif

ifneq ($(BOARD_CHARGER_DISABLE_INIT_BLANK),)
    LOCAL_CFLAGS += -DCHARGER_DISABLE_INIT_BLANK=$(BOARD_CHARGER_DISABLE_INIT_BLANK)
endif

ifneq ($(BOARD_CHARGER_ENABLE_SUSPEND),)
    LOCAL_CFLAGS += -DCHARGER_ENABLE_SUSPEND=$(BOARD_CHARGER_ENABLE_SUSPEND)
endif
