/*
 * Copyright 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package android.hardware.security.see.hwcrypto;

import android.hardware.security.see.hwcrypto.DerivedKeyResult;
import android.hardware.security.see.hwcrypto.IHwCryptoOperations;
import android.hardware.security.see.hwcrypto.IOpaqueKey;
import android.hardware.security.see.hwcrypto.KeyPolicy;

/*
 * Higher level interface to access device-specific keys. It shares definitions with the HwCrypto
 * service but it is intended to be implemented separately (although it can coexist in the same
 * application). Opaque Keys returned from this service are intended to be used through the HWCrypto
 * service, while clear keys are intended to be used directly by the caller. Keys generated by
 * calling <code>hwkeyDeriveVersioned</code> are tied to the caller version using the
 * <code>dicePolicyForKeyVersion</code> parameter. On the first use of the interface, if the caller
 * doesn't already have a DICE policy for a key, the caller can pass NULL for this parameter.
 * The interface will return a current DICE policy along with the generated key in
 * <code>DerivedKeyResult</code>. To generate the same key again, the caller will need to provide
 * the provided DICE policy. If the provided <code>dicePolicyForKeyVersion</code> match the current
 * vesions a NULL will be returned along with the generated key under <code>DerivedKeyResult</code>.
 * If the provided <code>dicePolicyForKeyVersion</code> is not current, a current DICE policy will
 * be returned on <code>DerivedKeyResult</code>. This can be seen on the following diagram:
 *
 * ```sequence-diagram
 *
 * title: dicePolicyForKeyVersion relation to derived keys and current version
 *
 * participant Client as cl
 * participant IHwCryptoDeviceKeyAccess as hwc
 *
 * cl->hwc: (key1, dice_policy_v1) = hwkeyDeriveVersioned(dicePolicyForKeyVersion = NULL)
 * cl->hwc: (key1, NULL) = hwkeyDeriveVersioned(dicePolicyForKeyVersion = dice_policy_v1)
 * cl->hwc: (key1, NULL) = hwkeyDeriveVersioned(dicePolicyForKeyVersion = dice_policy_v1)
 *
 * Note right of hwc: At this point, one of the components version changes
 *
 * cl->hwc: (key1, dice_policy_v2) = hwkeyDeriveVersioned(dicePolicyForKeyVersion = dice_policy_v1)
 * cl->hwc: (key1, dice_policy_v2) = hwkeyDeriveVersioned(dicePolicyForKeyVersion = dice_policy_v1)
 * cl->hwc: (key2, NULL) = hwkeyDeriveVersioned(dicePolicyForKeyVersion = dice_policy_v2)```
 *
 */
interface IHwCryptoDeviceKeyAccess {
    parcelable ClearKeyPolicy {
        /*
         * Indicates the desired key size. It will be used to calculate how many bytes of key
         * material should be returned.
         */
        int keySize;
    }

    union DerivedKeyPolicy {
        /*
         * Policy for the newly derived opaque key. Defines how the key can be used and its type.
         */
        KeyPolicy opaqueKey;

        /*
         * If used we will derive a clear key and pass it back as an array of bytes on
         * <code>HwCryptoKeyMaterial::explicitKey</code>.
         */
        ClearKeyPolicy clearKey;
    }

    parcelable DerivedKeyParameters {
        /*
         * If true, the derived key will be consistent and shared across the entire
         * family of devices, given the same input (shared key). If false, the derived key will
         * be unique to the particular device it was derived on.
         */
        boolean batchKey = false;

        /*
         * Policy for the newly derived key. Depending on its type, either a clear or opaque key
         * will be derived.
         */
        DerivedKeyPolicy keyPolicy;

        /*
         * Policy used to derive keys tied to specific versions. Using this parameter
         * the caller can tie a derived key to a minimum version of itself, so in the future only
         * iself or a more recent version can derive the same key. This parameter is opaque to the
         * caller and it can be encrypted in the case the client doesn't have permission to know the
         * dice chain. In the case it is encrypted, it should also be salted to avoid reusing the
         * same encrypted blob.
         * If a NULL value is passed on this parameter,
         * <code>DerivedKeyResult.dicePolicyForKeyVersion</code> will generate and return a DICE
         * policy corresponding to the current version as part of its result. If an old policy is
         * used, this function will return the most recent policy as part of the result. If the
         * policy is current, NULL will be returned as the policy.
         * When implementing this function, this parameter shall be one of the components fed
         * to the KDF context and it needs to be checked against the caller DICE certificate before
         * being used.
         */
        @nullable byte[] dicePolicyForKeyVersion;

        /*
         * An arbitrary set of bytes incorporated into the key derivation. May have
         * an implementation-specific maximum length, but it is guaranteed to accept
         * at least 32 bytes.
         */
        byte[] context;
    }

    /*
     * getHwCryptoOperations() - Returns an interface used to work on opaque keys. This interface
     *                           can also be used to operate on any opaque key generated by
     *                           hwkeyDeriveVersioned, even if this key has been generated after
     *                           retrieving a IHwCryptoOperations binder object, as long as the
     *                           parent IHwCryptoDeviceKeyAccess is not dropped between retrieving
     *                           the IHwCryptoOperations binder object and deriving the key.
     *                           IHwCryptoOperations can also be used to create opaque keys that
     *                           are not bound to the device.
     *
     * Return:
     *      IHwCryptoOperations on success
     */
    IHwCryptoOperations getHwCryptoOperations();

    /*
     * hwkeyDeriveVersioned() - Derive a versioned, device-specific or batch key from
     *                          provided context.
     *
     * @parameters:
     *      Parameters used for the key derivation. See <code>DerivedKeyParameters</code> on this
     *      file for more information.
     *
     * Return:
     *      Ok(DerivedKeyResult) on success, service specific error based on
     *      <code>HalErrorCode</code> otherwise.
     */
    DerivedKeyResult hwkeyDeriveVersioned(in DerivedKeyParameters parameters);
}
