/*
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.hardware.security.keymint;

import android.hardware.security.keymint.DeviceInfo;
import android.hardware.security.keymint.MacedPublicKey;
import android.hardware.security.keymint.ProtectedData;
import android.hardware.security.keymint.RpcHardwareInfo;

/**
 * An IRemotelyProvisionedComponent is a secure-side component for which certificates can be
 * remotely provisioned. It provides an interface for generating asymmetric key pairs and then
 * creating a CertificateRequest that contains the generated public keys, plus other information to
 * authenticate the request origin. The CertificateRequest can be sent to a server, which can
 * validate the request and create certificates.
 *
 * This interface does not provide any way to use the generated and certified key pairs. It's
 * intended to be implemented by a HAL service that does other things with keys (e.g. Keymint).
 *
 * The root of trust for secure provisioning is something called the DICE Chain. The DICE Chain is a
 * chain of public key certificates, represented as COSE_Sign1 objects containing CBOR Web Tokens
 * (CWT) which have descriptions about the stage of firmware being signed, including a COSE_Key
 * representation of that stage's CDI_public_key. The "root" of the DICE chain is a device-unique
 * public key, denoted UDS_Pub. All public keys in the DICE certificate are device-unique. The
 * private key from each certified keypair in the chain is used to sign the next certificate in the
 * chain. The final, "leaf" certificate contains a public key, denoted CDI_Leaf_Pub, whose
 * corresponding private key, denoted CDI_Leaf_Priv, is available for use by the
 * IRemotelyProvisionedComponent.
 *
 * DICE Chain Design
 * =================
 *
 * For a more exhaustive and thorough look at DICE and the implementation used within this protocol,
 * please see: https://pigweed.googlesource.com/open-dice/+/HEAD/docs/specification.md
 *
 * The DICE Chain is designed to mirror the boot stages of a device, and to prove the content and
 * integrity of each firmware image. In a proper DICE Chain, each boot stage hashes its own private
 * key material with the code and any relevant configuration parameters of the next stage to produce
 * a key pair for the next stage. Each stage also uses its own private key to sign the public key of
 * the next stage, including in the certificate the hash of the next firmware stage, then loads the
 * next stage, passing the private key material and certificate to it in a manner that does not leak
 * its own private key to later boot stages. The UDS_Keypair is generated by immutable code (e.g.
 * ROM), from a device-unique secret. After the device-unique secret is used, it must be made
 * unavailable to any later boot stage.
 *
 * In this way, booting the device incrementally builds a certificate chain that (a) identifies and
 * validates the integrity of every stage and (b) contains a set of public keys that correspond to
 * private keys, one known to each stage. Any stage can compute the secrets of all later stages
 * (given the necessary input), but no stage can compute the secret of any preceding stage. Updating
 * the firmware or configuration of any stage changes the key pair of that stage, and of all
 * subsequent stages, and no attacker who compromised the previous version of the updated firmware
 * can know or predict the post-update key pairs. It is recommended and expected that the DICE Chain
 * is constructed using the Open Profile for DICE.
 *
 * When the provisioning server receives a message signed by UDS_Leaf_Priv and containing a DICE
 * chain that chains from UDS_Pub to CDI_Leaf_Pub, it can be certain that (barring vulnerabilities
 * in some boot stage), the CertificateRequest came from the device associated with UDS_Pub, running
 * the specific software identified by the certificates in the chain. If the server has some
 * mechanism for knowing the hash values of compromised stages, it can determine whether signing
 * certificates is appropriate.
 *
 * Degenerate DICE Chains
 * ======================
 *
 * While a proper DICE Chains, as described above, reflects the complete boot sequence from boot ROM
 * to the secure area image of the IRemotelyProvisionedComponent, it's also possible to use a
 * "degenerate" DICE Chain which consists only of a single, self-signed certificate containing the
 * public key of a hardware-bound key pair. This is an appopriate solution for devices which haven't
 * implemented everything necessary to produce a proper DICE Chain, but can derive a unique key pair
 * in the secure area. In this degenerate case, UDS_Pub is the same as CDI_Leaf_Pub.
 *
 * DICE Chain Privacy
 * ===========
 *
 * Because the DICE Chain constitutes an unspoofable, device-unique identifier, special care is
 * taken to prevent its availability to entities who may wish to track devices. Three precautions
 * are taken:
 *
 * 1) The DICE chain is only handled by the native RKPD service on the HLOS and is not exposed to
 *    apps running on device.
 *
 * 2) The CDI_Leaf_Priv key cannot be used to sign arbitrary data.
 *
 * 3) Backend infrastructure does not correlate UDS_Pub with the certificates signed and sent back
 *    to the device.
 *
 * @hide
 */
@VintfStability
interface IRemotelyProvisionedComponent {
    const int STATUS_FAILED = 1;
    const int STATUS_INVALID_MAC = 2;

    /**
     * @return info which contains information about the underlying IRemotelyProvisionedComponent
     *         hardware, such as version number, component name, author name, and supported curve.
     */
    RpcHardwareInfo getHardwareInfo();

    /**
     * generateKeyPair generates a new ECDSA P-256 key pair that can be attested by the remote
     * server.
     *
     * @param out MacedPublicKey macedPublicKey contains the public key of the generated key pair,
     *        MACed so that generateCertificateRequest can easily verify, without the
     *        privateKeyHandle, that the contained public key is for remote certification.
     *
     * @return data representing a handle to the private key. The format is implementation-defined,
     *         but note that specific services may define a required format. KeyMint does.
     */
    byte[] generateEcdsaP256KeyPair(out MacedPublicKey macedPublicKey);

    /**
     * generateCertificateRequest creates a certificate signing request to be sent to the
     * provisioning server.
     *
     * @param in MacedPublicKey[] keysToSign contains the set of keys to certify. The
     *        IRemotelyProvisionedComponent must validate the MACs on each key.  If any entry in the
     *        array lacks a valid MAC, the method must return STATUS_INVALID_MAC.
     *
     * @param in challenge contains a byte string from the provisioning server which will be signed
     *        as part of the CSR structure.
     *
     * @return the following CBOR structure (Csr) serialized into a byte array:
     *
     * Csr = [
     *    version: 3,              ; The CDDL Schema version.
     *    AdditionalDkSignatures,
     *    DiceCertChain,
     *    SignedData
     * ]
     *
     * SignedData = [                    ; COSE_Sign1 (untagged)
     *     protected: bstr .cbor { 1 : AlgorithmEdDSA / AlgorithmES256 },
     *     unprotected: {},
     *     payload: bstr .cbor SignedDataPayload,
     *     signature: bstr               ; PureEd25519(SigningKey, bstr .cbor SignedCsrInput) /
     *                                   ; ECDSA(SigningKey, bstr .cbor SignedCsrInput)
     * ]
     *
     * SignedCsrInput = [                ; Sig_structure for SignedData
     *     context: "Signature1",
     *     protected: bstr .cbor { 1 : AlgorithmEdDSA / AlgorithmES256 },
     *     external_aad: bstr .size 0,
     *     payload: bstr .cbor SignedDataPayload
     * ]
     *
     * SignedDataPayload = [             ; CBOR Array defining the payload for SignedData
     *     DeviceInfo,       ; Defined in DeviceInfo.aidl
     *     challenge: .bstr, ; Provided by the method parameters
     *     KeysToSign,       ; Provided by the method parameters
     * ]
     *
     * KeysToSign = [ * PublicKey ]   ; Please see MacedPublicKey.aidl for the PublicKey definition.
     *
     * ; AdditionalUdsSignatures allows the platform to provide additional certifications
     * ; for the UDS_Public_Key. For example, this could be provided by the hardware vendor,
     * ; who certifies all of their devices. The SignerName is a free-form string describing
     * ; who generated the signature.
     * AdditionalUdsSignatures = {
     *     + SignerName => UdsCertChain
     * }
     *
     * ; SignerName is a string identifier that indicates both the signing authority as
     * ; well as the format of the UdsCertChain
     * SignerName = tstr
     *
     * UdsCertChain = [
     *     2* X509Certificate       ; Root -> ... -> Leaf. "Root" is the vendor self-signed
     *                              ; cert, "Leaf" contains UDS_Public. There may also be
     *                              ; intermediate certificates between Root and Leaf.
     * ]
     *
     * ; A bstr containing a DER-encoded X.509 certificate (RSA, NIST P-curve, or edDSA)
     * X509Certificate = bstr
     *
     * ; The DICE Chain contains measurements about the device firmware.
     * ; The first entry in the DICE Chain is the UDS_Public_Key, encoded as a COSE_key. All entries
     * ; after the first describe a link in the boot chain (e.g. bootloaders: BL1, BL2, ... BLN)
     * ; Note that there is no DICE Chain Entry for DK_pub, only a "bare" COSE_key.
     * Dcc = [
     *     PubKeyEd25519 / PubKeyECDSA256,  ; UDS_Public_Key
     *     + DiceChainEntry,                ; Root -> leaf (KM_pub)
     * ]
     *
     * ; This is the signed payload for each entry in the DCC. Note that the "Configuration
     * ; Input Values" described by the Open Profile are not used here. Instead, the Dcc
     * ; defines its own configuration values for the Configuration Descriptor field. See
     * ; the Open Profile for DICE for more details on the fields. All hashes are SHA256.
     * DiceChainEntryPayload = {                    ; CWT [RFC8392]
     *     1 : tstr,                                ; Issuer
     *     2 : tstr,                                ; Subject
     *     -4670552 : bstr .cbor PubKeyEd25519 /
     *                bstr .cbor PubKeyECDSA256,    ; Subject Public Key
     *     -4670553 : bstr                          ; Key Usage
     *
     *     ; NOTE: All of the following fields may be omitted for a "Degenerate DCC", as
     *     ;       described by IRemotelyProvisionedComponent.aidl.
     *     -4670545 : bstr,                         ; Code Hash
     *     ? -4670546 : bstr,                       ; Code Descriptor
     *     ? -4670547 : bstr,                       ; Configuration Hash
     *     -4670548 : bstr .cbor {                  ; Configuration Descriptor
     *         ? -70002 : tstr,                         ; Component name
     *         ? -70003 : int,                          ; Firmware version
     *         ? -70004 : null,                         ; Resettable
     *     },
     *     -4670549 : bstr,                         ; Authority Hash
     *     ? -4670550 : bstr,                       ; Authority Descriptor
     *     -4670551 : bstr,                         ; Mode
     * }
     *
     * ; Each entry in the Dcc is a DiceChainEntryPayload signed by the key from the previous entry
     * ; in the Dcc array.
     * DiceChainEntry = [                            ; COSE_Sign1 (untagged)
     *     protected : bstr .cbor { 1 : AlgorithmEdDSA / AlgorithmES256 },
     *     unprotected: {},
     *     payload: bstr .cbor DiceChainEntryPayload,
     *     signature: bstr ; PureEd25519(SigningKey, bstr .cbor DiceChainEntryInput) /
     *                     ; ECDSA(SigningKey, bstr .cbor DiceChainEntryInput)
     *                     ; See RFC 8032 for details of how to encode the signature value
     *                     ; for Ed25519.
     * ]
     *
     * DiceChainEntryInput = [
     *     context: "Signature1",
     *     protected: bstr .cbor { 1 : AlgorithmEdDSA / AlgorithmES256 },
     *     external_aad: bstr .size 0,
     *     payload: bstr .cbor DiceChainEntryPayload
     * ]
     *
     * ; The following section defines some types that are reused throughout the above
     * ; data structures.
     * PubKeyX25519 = {                 ; COSE_Key
     *      1 : 1,                      ; Key type : Octet Key Pair
     *     -1 : 4,                      ; Curve : X25519
     *     -2 : bstr                    ; Sender X25519 public key
     * }
     *
     * PubKeyEd25519 = {                ; COSE_Key
     *     1 : 1,                       ; Key type : octet key pair
     *     3 : AlgorithmEdDSA,          ; Algorithm : EdDSA
     *     -1 : 6,                      ; Curve : Ed25519
     *     -2 : bstr                    ; X coordinate, little-endian
     * }
     *
     * PubKeyEcdhP256 = {               ; COSE_Key
     *      1 : 2,                      ; Key type : EC2
     *      -1 : 1,                     ; Curve : P256
     *      -2 : bstr                   ; Sender X coordinate
     *      -3 : bstr                   ; Sender Y coordinate
     * }
     *
     * PubKeyECDSA256 = {               ; COSE_Key
     *     1 : 2,                       ; Key type : EC2
     *     3 : AlgorithmES256,          ; Algorithm : ECDSA w/ SHA-256
     *     -1 : 1,                      ; Curve: P256
     *     -2 : bstr,                   ; X coordinate
     *     -3 : bstr                    ; Y coordinate
     * }
     *
     * AlgorithmES256 = -7
     * AlgorithmEdDSA = -8
     */
    byte[] generateCertificateRequest(in MacedPublicKey[] keysToSign, in byte[] challenge);
}
