/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.hardware.rpmb;

@VintfStability
parcelable RpmbMessageFrameNormal {
    // Padding for the frame
    byte[196] stuff;
    // Message Authentication Code OR the Authentication key (used only for programming
    // authentication key).
    byte[32] key_or_mac;
    // Data to be written or read by signed access
    byte[256] data;
    // Random number generated by the host for the requests and copied to response by the RPMB
    // engine.
    byte[16] nonce;
    // Total amount of successful authenticated data write operations.
    byte[2] write_counter;
    // Logical block address of data to be programmed to or read from the RPMB region.
    byte[2] address;
    // Number of 256-byte logical blocks requested to be read or programmed.
    byte[2] block_count;
    // Operation result
    byte[2] result;
    // Request Message Type / Response Message Type
    byte[2] req_resp;
}
