package android.hardware.security.see.hwcrypto.base_types;

// TODO: Placeholder for Secure Hal Error codes. Current list based on Trusty err.h header file.
@Backing(type="int")
enum HalErrorCode {
    NoError = 0,
    GenericError = -1,
    NotFound = -2,
    NotReady = -3,
    NoMessage = -4,
    NoMemory = -5,
    ALreadyStarted = -6,
    NotValid = -7,
    InvalidArgs = -8,
    BufferTooSmall = -9,
    NotSuspended = -10,
    ObjectDestroyed = -11,
    NotBlocked = -12,
    TimedOut = -13,
    AlreadyExists = -14,
    ChannelClosed = -15,
    Offline = -16,
    NotAllowed = -17,
    BadPath = -18,
    AlreadyMounted = -19,
    IoError = -20,
    NotADir = -21,
    NotAFile = -22,
    RecursedTooDeep = -23,
    NotSupported = -24,
    TooBig = -25,
    Cancelled = -26,
    NotImplemented = -27,
    ChecksumFail = -28,
    CrcFail = -29,
    CmdUnknown = -30,
    BadState = -31,
    BadLen = -32,
    Busy = -33,
    ThreadDettached = -34,
    I2cNack = -35,
    AlreadyExpired = -36,
    OutOfRange = -37,
    NotConfigured = -38,
    NotMounted = -39,
    Fault = -40,
    NoResources = -41,
    BadHandle = -42,
    AccessDenied = -43,
    PartialWrite = -44,
}
