; CDDL for the Secret Management API.
; Also see secretManagement method in ISecretkeeper.aidl

; ProtectedRequestPacket is used by client for accessing Secret Management API
; in Secretkeeper service. The service returns ProtectedResponsePacket of the corresponding type.

; ProtectedRequestPacket & ProtectedResponsePacket are (encrypted) wrappers
; on RequestPacket & ResponsePacket
; The API operation required is encoded using Opcode, the arguments using Opcode, Params, Result.

ProtectedRequestPacket = ProtectedGetVersionRequest / ProtectedStoreRequest / ProtectedGetRequest
ProtectedResponsePacket = ProtectedGetVersionResponse / ProtectedStoreResponse / ProtectedGetResponse

; TODO(b/291228560): Link to KeyL & KeyR derivation
ProtectedGetVersionRequest = ProtectedRequestPacket<GetVersionRequestPacket, KeyL>
ProtectedGetVersionResponse = ProtectedResponsePacket<GetVersionResponsePacket, KeyL>
ProtectedStoreRequest = ProtectedRequestPacket<StoreRequestPacket, KeyL>
ProtectedStoreResponse = ProtectedResponsePacket<StoreResponsePacket, KeyR>
ProtectedGetRequest = ProtectedRequestPacket<GetRequestPacket, KeyL>
ProtectedGetResponse = ProtectedResponsePacket<GetResponsePacket, KeyR>

GetVersionRequestPacket = RequestPacket<GetVersionOpcode, GetVersionParams>
GetVersionResponsePacket = ResponsePacket<GetVersionResult>
StoreRequestPacket = RequestPacket<StoreOpcode, StoreParams>
StoreResponsePacket = ResponsePacket<StoreResult>
GetRequestPacket = RequestPacket<GetOpcode, GetParams>
GetResponsePacket = ResponsePacket<GetResult>

RequestPacket<Opcode, Params> = [
    Opcode,
    Params
]
ResponsePacket<Result> = ResponsePacketError / ResponsePacketSuccess<Result>

ResponsePacketSuccess = [
    0,                          ; Indicates successful Response
    result : Result
]
ResponsePacketError = [
    error_code: ErrorCode,      ; Indicate the error
    error_message: tstr         ; Additional human-readable context
]

Opcode = &(
    GetVersionOpcode: 1,     ; Get version of the SecretManagement API
    StoreOpcode: 2,          ; Store a secret
    GetOpcode: 3,            ; Get the secret
)

GetVersionParams = ()
GetVersionResult = (version : int)

StoreParams = (
    id : bstr .size 64              ; Unique idnetifier of the secret
    secret : bstr .size 32,
    sealing_policy : DicePolicy,    ; See DicePolicy.cddl for definition of DicePolicy
)
StoreResult = ()

GetParams = (
    id : bstr .size 64              ; Unique idnetifier of the secret
    ? updated_sealing_policy : DicePolicy,  ; See DicePolicy.cddl for definition of DicePolicy
)
GetResult = (secret : bstr .size 32)


ProtectedRequestPacket<Payload, Key> = CryptoPayload<Payload, Key>
ProtectedResponsePacket<Payload, Key> = ProtectedResponseError
                                    / ProtectedResponseSuccess<Payload, Key>

ProtectedResponseSuccess<Payload, Key> = [
    0,                                   ; Indicates successful crypto operations. Note: Payload
                                         ; may contain Error from functional layer.
    message: CryptoPayload<Payload, Key>         ; message is the encrypted payload
]

ProtectedResponseError = [
    error_code: CryptoErrorCode,           ; Indicates the error. This is in cleartext & will be
                                           ; visible to Android. These are errors from crypto
                                           ; layer & indicates the request could not even be read
    message: tstr                          ; Additional human-readable context
]

CryptoPayload<Payload, Key> = [         ; COSE_Encrypt0 (untagged), [RFC9052 s5.2]
    protected: bstr .cbor {
        1 : 3,                  ; Algorithm: AES-GCM mode w/ 256-bit key, 128-bit tag
        4 : bstr                ; key identifier, uniquely identifies the session
                                ; TODO(b/291228560): Refer to the Key Exchange spec.

    },
    unprotected: {
        5 : bstr .size 12          ; IV
    },
    ciphertext : bstr     ; AES-GCM-256(Key, .cbor Payload)
                          ; AAD for the encryption is CBOR-serialized
                          ; Enc_structure (RFC 8152 s5.3) with empty external_aad.
]

; TODO(b/291224769): Create a more exhaustive set of CryptoErrorCode
CryptoErrorCode = &(
    CryptoErrorCode_SessionExpired: 1,
)

; TODO(b/291224769): Create a more exhaustive set of ErrorCodes
ErrorCode = &(
    ErrorCode_RequestMalformed: 1,
)
