; CDDL for the Secret Management API.
; Also see secretManagement method in ISecretkeeper.aidl

; ProtectedRequestPacket is used by client for accessing Secret Management API
; in Secretkeeper service. The service returns ProtectedResponsePacket of the corresponding type.

; ProtectedRequestPacket & ProtectedResponsePacket are (encrypted) wrappers
; on RequestPacket & ResponsePacket
; The API operation required is encoded using Opcode, the arguments using Opcode, Args, Ret params.

ProtectedRequestPacket = ProtectedGetVersionRequest / ProtectedStoreRequest / ProtectedGetRequest
ProtectedResponsePacket = ProtectedGetVersionResponse / ProtectedStoreResponse / ProtectedGetResponse

; TODO(b/291224769): Link to KeyL & KeyR derivation
ProtectedGetVersionRequest = ProtectedRequestPacket<GetVersionRequestPacket, KeyL>
ProtectedGetVersionResponse = ProtectedResponsePacket<GetVersionResponsePacket, KeyL>
ProtectedStoreRequest = ProtectedRequestPacket<StoreRequestPacket, KeyL>
ProtectedStoreResponse = ProtectedResponsePacket<StoreResponsePacket, KeyR>
ProtectedGetRequest = ProtectedRequestPacket<GetRequestPacket, KeyL>
ProtectedGetResponse = ProtectedResponsePacket<GetResponsePacket, KeyR>

GetVersionRequestPacket = RequestPacket<GetVersionOpcode, GetVersionArgs>
GetVersionResponsePacket = ResponsePacket<GetVersionOpcode, GetVersionResult>
StoreRequestPacket = RequestPacket<StoreOpcode, StoreArgs>
StoreResponsePacket = ResponsePacket<StoreOpcode, StoreResult>
GetRequestPacket = RequestPacket<GetOpcode, GetArgs>
GetResponsePacket = ResponsePacket<GetOpcode, GetResult>

RequestPacket<Opcode, Args> = [
    Opcode,
    Args
]
ResponsePacket<Result> = [
    error_code: ErrorCode,                    ; Indicate the error
    message: Result / ErrorMessage            ; message is the encrypted payload
                                              ; when error_code == ErrorCode_Ok
                                              ; otherwise it is ErrorMessage
]

Opcode = &(
    GetVersionOpcode: 1,     ; Get version of the SecretManagement API
    StoreOpcode: 2,          ; Store a secret
    GetOpcode: 3,            ; Get the secret
)

GetVersionArgs = ()
GetVersionResult = (version : int)
StoreArgs = (
    key : EntryId,
    value : bstr .size 64,
    sealing_policy : DicePolicy,
)
StoreResult = ()
GetArgs = (
    key : EntryId,
    ? updated_sealing_policy : DicePolicy,
)
GetResult = (secret : bstr .size 64)

; Unique identifier of the secret in Secretkeeper database
EntryId = [
    uuid : bstr .size 64           ; Unique Id of the client
    entry_type : EntryType         ; Type of entry, can be used to keep mutiple type of secrets
]
EntryType = &(
    VmSecret: 1,                    ; Indicating the entry is VM secret.
)

ProtectedRequestPacket<Payload, Key> = CryptoPayload<Payload, Key>
ProtectedResponsePacket<Payload, Key> = [
    error_code: CryptoErrorCode,           ; Indicate the error. This is in cleartext & will be
                                           ; visible to Android.These are errors from to crypto
                                           ; layer & indicates the request could not even be read.
    message: CryptoPayload<Payload, Key> / ErrorMessage          ; message is the encrypted payload
                                                                 ; when error_code == ErrorCode_Ok
                                                                 ; otherwise it is ErrorMessage
]

CryptoPayload<Payload, K> = [         ; COSE_Encrypt0
    protected: bstr .cbor {
        1 : 3,    ; Algorithm: AES-GCM mode w/ 256-bit key, 128-bit tag
        4 : bstr  ; Key identifier, unique identifies the session
    },
    unprotected: {
        5 : bstr .size 12          ; IV
    },
    ciphertext : bstr     ; AES-GCM-256(K, .cbor Payload)
                          ; AAD for the encryption is CBOR-serialized
                          ; Enc_structure (RFC 8152 s5.3) with empty external_aad.
]

; TODO(b/291224769): Create a more exhaustive set of CryptoErrorCode
CryptoErrorCode = &(
    CryptoErrorCode_Ok: 0,
    CryptoErrorCode_SessionExpired: 1,
)

; TODO(b/291224769): Create a more exhaustive set of ErrorCodes
ErrorCode = &(
    ErrorCode_Ok: 0,
    ErrorCode_RequestMalformed: 1,
)
; Additional context can be added to the error using ErrorMessage.
ErrorMessage =  tstr
