ExplicitKeyDiceCertChain = [
    1, ; version, hopefully will never change
    DiceCertChainInitialPayload,
    * DiceChainEntry
]

DiceCertChainInitialPayload = {
    -4670552 : bstr .cbor PubKeyEd25519 /
               bstr .cbor PubKeyECDSA256 /
               bstr .cbor PubKeyECDSA384 ; subjectPublicKey
}

; INCLUDE generateCertificateRequestV2.cddl for: PubKeyEd25519, PubKeyECDSA256, PubKeyECDSA384, DiceChainEntry
; from hardware/interfaces/security/rkp/aidl/android/hardware/security/keymint/
