Identity = [
    1, ; Version
    cert_chain: bstr .cbor ExplicitKeyDiceCertChain,
    policy: bstr .cbor DicePolicy / nil,
]

; INCLUDE ExplicitKeyDiceCertChain.cddl for: ExplicitKeyDiceCertChain
; INCLUDE DicePolicy.cddl for: DicePolicy
