KESignature = [ ; COSE_Sign1 (untagged) [RFC9052 s4.2]
    protected: bstr .cbor KESignatureProtected,
    unprotected: {},
    payload: nil,       ; session ID payload to be transported separately
    signature: bstr     ; PureEd25519(privateKey, KESignatureSigStruct) /
                        ; ECDSA(privateKey, KESignatureSigStruct)
]

KESignatureProtected = {
    1 : AlgorithmEdDSA / AlgorithmES256,
    ; TODO: add protected fields
}

KESignatureSigStruct = [ ; Sig_structure for KESignature [ RFC9052 s4.4]
    context: "Signature1",
    protected: bstr KESignatureProtected,
    external_aad: bstr .size 0,
    payload: bstr,       ; session ID payload provided separately
]
