/*
 * Copyright (C) 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

SignedConnectionRequesProtected = {
    1 : AlgorithmEdDSA / AlgorithmES256,
}

SignedConnectionRequest = [ ; COSE_Sign1 (untagged) [RFC9052 s4.2]
    protected: bstr .cbor SignedConnectionRequesProtected,
    unprotected: {},
    payload: bstr .cbor ConnectionRequest,
    signature: bstr     ; PureEd25519(privateKey, SignedResponseSigStruct) /
                        ; ECDSA(privateKey, SignedResponseSigStruct)
]

ConnectionRequestSigStruct = [ ; Sig_structure for SignedConnectionRequest [ RFC9052 s4.4]
    context: "Signature1",
    body_protected: bstr .cbor SignedConnectionRequesProtected,
    external_aad: bstr .size 0,
    payload: bstr .cbor ConnectionRequest,
]

ConnectionRequest [
    challenge: bstr .size 32,
    feTransportID: bstr .size 2, ; transport ID of the AuthMgr FE
    beTransportID: bstr .size 2, ; transport ID of the AuthMgr BE
]

AlgorithmES256 = -7              ; [RFC9053 s2.1]
AlgorithmEdDSA = -8              ; [RFC9053 s2.2]
